# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: packwiz-artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install packwiz
      run: go install github.com/packwiz/packwiz@latest

    - name: Create the pack
      run: packwiz modrinth export

    - name: Upload the pack
      uses: actions/upload-artifact@v4
      with:
        name: qol-pack-artifacts-${{ steps.ref.outputs.branch }}
        path: ./*.mrpack
        compression-level: 9
